### ISSUE TITLE
"Protobuf gencode version" warning

### ISSUE THREAD

**Issue by mateenkasim** [authzed/authzed-py#201]
Just bumped from 0.16.0 to 0.18.1, and I'm getting these warnings now, looks like fallout from https://github.com/authzed/authzed-py/pull/191.

```
/.venv/lib64/python3.11/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.3 is older than the runtime version 5.28.0 at authzed/api/v1/core.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
  warnings.warn(
/.venv/lib64/python3.11/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.3 is older than the runtime version 5.28.0 at authzed/api/v1/error_reason.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
  warnings.warn(
/.venv/lib64/python3.11/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.3 is older than the runtime version 5.28.0 at authzed/api/v1/experimental_service.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
  warnings.warn(
/.venv/lib64/python3.11/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.3 is older than the runtime version 5.28.0 at authzed/api/v1/permission_service.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
  warnings.warn(
/.venv/lib64/python3.11/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.3 is older than the runtime version 5.28.0 at authzed/api/v1/debug.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
  warnings.warn(
/.venv/lib64/python3.11/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.3 is older than the runtime version 5.28.0 at authzed/api/v1/schema_service.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
  warnings.warn(
/.venv/lib64/python3.11/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.3 is older than the runtime version 5.28.0 at authzed/api/v1/watch_service.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
  warnings.warn(
```

I don't think there's a real breaking change, so I'm just gonna filter the warning out, but it seemed worth noting.

**Comment by tstirrat15** [comment]
Hmm... [This test](https://github.com/authzed/authzed-py/blob/main/.github/workflows/test.yaml#L46-L79) should theoretically catch that. Gencode being older than runtime code should also be generally okay, as long as semver boundaries aren't being crossed.

That said, the intended use case is that the version of `protobuf` used to generate the code is the same as the version used to run the code. I think the vision is that anyone consuming a gRPC service is doing their own code generation, so us doing the generation and providing the lib is breaking that expectation somewhat. We also don't want to be too prescriptive as library authors and provide too narrow a dependency range that then breaks someone's usage who needs a different version of protobuf for whatever reason.

I think the fix for you in the meantime would be to explicitly put `protobuf==5.27.3` into your dependency management file. I can add that to an FAQ or something if that ends up working.

**Comment by mateenkasim** [comment]
I hear you, and I agree with you that the dependency range should be broad. After some digging, it turns out this is a new warning as of `protobuf==5.28.0`, so I'm gonna close this issue as they hash this one out. 
- https://github.com/protocolbuffers/protobuf/issues/18096
- https://github.com/grpc/grpc/issues/37609

Honestly, I don't think it's uncommon for a product to provide the gRPC client to its customers, so this warning is a little weird, especially for a minor version difference. If I happened to use two different gRPC clients in one project, chances are slim that they'd match protobuf gencode versions perfectly. For now though, filtering the warning or locking the protobuf version both work well for me.
